### PR TITLE
SONAR-23600 Update the SonarQube Server logo

### PR DESCRIPTION
**Pull request by carminevassallo**

### CODE REVIEW

**Review by jCOTINEAU — APPROVED** [review]
lgtm.

**Comment by philippe-perrin-sonarsource** [comment]
Hey there. Can you provide more information as to how we can validate your change?

**Comment by carminevassallo** [comment]
Hi @philippe-perrin-sonarsource,

The logo is supposed to be used in the Helm Chart description file as the chart's `icon` (we updated the expected value already, as you can check [here](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/Chart.yaml#L13)). As per the [Helm Chart documentation](https://helm.sh/docs/topics/charts/#the-chartyaml-file), the icon accepts both PNG and SVG images and the new logo to be used as been agreed with PMs.

Feel free to ping me if you need more details :)

**Comment by philippe-perrin-sonarsource** [comment]
I assume [this](https://artifacthub.io/packages/helm/sonarqube/sonarqube) is where we actually see it live, am I correct?

Once merged, could it be that an older version of that page (or the current one for example) still relies on the former logo? I'm asking because I'm wondering what can break with the removal of the `SonarQubeLogo.svg` file.

Wouldn't it be safer to keep the same file name and to change the content only?

**Comment by carminevassallo** [comment]
Hi @philippe-perrin-sonarsource, 

I think we should be safe, as. the logo gets uploaded to ArtifactHUB when we release it (e.g., the current [Helm chart](https://artifacthub.io/packages/helm/sonarqube/sonarqube)'s logo is available at https://artifacthub.io/image/5d85ec41-d8ea-44e8-b9a8-c774ad6aa0f5@1x).

**Review by philippe-perrin-sonarsource — APPROVED** [review]

**Pull request merged**
